### ISSUE TITLE
Reaper on Fedora does not find Surge

### ISSUE THREAD

**Issue by masi** [surge-synthesizer/surge-synthesizer.github.io#159]
Scanning the VST folders does not bring up Surge. SurgeEffectsBank is found.

**Comment by baconpaul** [comment]
Hi!

Can you share some more information

1: Which version of surge, and how did you install it? 
2: Same for reaper?
3: Same for OS?
4: Any errors? if you run Reaper from terminal it often will show errors to stdout or logs.

I run surge 171 and nightly in reaper 6 in ubuntu 20 most days

My guess (guess) is you are running into the xcbutil1 vs 0 problem since fedora I think is a varient like buster and uses 0 but ubuntu where our build works is 1. The solution to this is to build it yourself from source usually. But that's just a guess

**Comment by masi** [comment]
Yep, ld complained about missing libxcb-cursor.so.0.
I installed the packge xcb-util-cursor (got xcb-util-cursor-0.1.3-10.fc32.x86_64) and Surge showed up.

I installed Surge by converting the .deb with alien into a .rpm. I had to force installation because of permission conflicts on / and another directory.
