### ISSUE TITLE
Digital Beauty not in line with the rest of the block

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#17]
<img width="542" alt="surge" src="https://user-images.githubusercontent.com/4966687/51799240-e2768d80-2227-11e9-931a-07dd0c1063ff.png">

**Comment by itsmedavep** [comment]
Ill look into this one. Im not sure if its a center alignment issue or something else. Basically, this text is wrapping due to the container being constrained to a desired line lenght. This caused the Heading to wrap. So Im trying to work out what the best fix is here. As far as I can tell right now this is left aligned and wrapped. 

Ill look into it though.

**Comment by itsmedavep** [comment]
I figured this out. It's dumb. For some reason the H1 tag has these 2 extra pixels before the font starts. 

The fix is either:

relative position for parent element
left: -2px;

or 

look into H1 styles and fix appropriately there.

**Comment by itsmedavep** [comment]
<img width="269" alt="screen shot 2019-02-04 at 8 42 31 pm" src="https://user-images.githubusercontent.com/11078351/52250457-b27d5900-28bd-11e9-8489-75df61b096d7.png">

This is done and was picked up on #56

**Comment by esaruoho** [comment]
closing, thanks for the fix @itsmedavep
