### ISSUE TITLE
https://surge-synthesizer.github.io/ says "Download for null"

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge-synthesizer.github.io#253]
![image](https://user-images.githubusercontent.com/271906/179160647-d1705e95-e447-4fb0-95e1-a764325d6cd1.png)

I think it meant to say "Download for FreeBSD" and link to https://www.freshports.org/audio/surge-synthesizer-xt-lv2/

OS: FreeBSD 13.1

Copied from https://github.com/surge-synthesizer/surge/issues/6364

**Comment by haenkel** [comment]
@baconpaul @mthierman
here is my proposal for the situation:

- If the button detects Linux, link to [releases-xt](https://github.com/surge-synthesizer/releases-xt/releases) instead of .deb
  This prevents people from asking for an .rpm as it sits right there next to .deb and tarball

- Let the button detect free-bsd as it is the only port outside of lin/win/mac.
  Link that to the BSD chapter of our unix-wiki-page which includes the links to the port,
  indicates clearly that it's not maintained by sst and isn't an outside link itself.
  Let @yurivict confirm it working and if the detection turns out to be tricky I am sure 
  yuri will happily provide a PR for this.

- Move the unix-page to surge/docs to increase it's findability
  and enable port-maintainers (or anyone) to send updating PRs 
  since you currently need write access to the repo to edit the wiki. 
  I can take care of this part including a first update of its content.

- Add a link to that document on the hero page saying "Surge Ports maintained by other projects"

- Any additional "NULL" detection links to prereqs the way it is done in 5cd4af38 
  until there is a better idea.

I hope this can be a solution that makes everybody happy 
and helps keeping this the inviting place we all want it to be.


btw @mthierman I don't want to mess around with the website since you are doing all the good work here
but if any of this sounds like I am trying to dump more work on you let me know, 
as that is not my intention and I am happy to help wherever I can.

**Comment by haenkel** [comment]
which one?

**Comment by baconpaul** [comment]
If linux -> releases-xt
if free-bud -> wiki
move docs + links
any other nulls say "here's how to build"

basically your idea seemed spot on to me!

**Comment by mkruselj** [comment]
This kind of makes the download slower for Linux people since they get one extra step to choose. Which is not what the big download button is all about, it should be immediate IMO...

**Comment by yurivict** [comment]
The button should auto-detect the OS, display the test accordingly, and change the link accordingly. No extra steps are required for anybody.

**Comment by haenkel** [comment]
@yurivict can you confirm that it works now?

**Comment by yurivict** [comment]
> can you confirm that it works now?

It works.

Common spelling is "FreeBSD", not "freeBSD" though (see https://www.freebsd.org/).

**Comment by haenkel** [comment]
>Common spelling is "FreeBSD", not "freeBSD" though

thanks, fixing in a minute

**Comment by mthierman** [comment]
Thanks for the work on this!

I think `os = "freeBSD";` should say `os = "Download for freeBSD";` (although it's not a direct download link.. hmm)

I wonder if we should also link system requirements for iOS/Android instead of hiding it?

**Comment by haenkel** [comment]
> (although it's not a direct download link.. hmm)
yeah thats why i didn't. I sent the pr before reading your message, but i think you can edit it you want to add stuff to it.
