### ISSUE TITLE
manual css work required for fixing list spacing of longer strings

### ISSUE THREAD

**Issue by esaruoho** [surge-synthesizer/surge-synthesizer.github.io#27]
currently it would appear that longer strings in lists will result in some extra padding (as pointed by the red arrow). maybe this can be tweaked?
![manual](https://user-images.githubusercontent.com/4966687/52046713-10bddb00-2550-11e9-9908-1170c562464f.jpg)

**Comment by itsmedavep** [comment]
This is the result of having the superscript tag in there for 4th and 5th.  Adding in the <sup> tag messes with line height. 

This fixes it. Alternatively,  not using the superscript will fix it as well. I only mention it because Im not sure that using the <sup> tag gets us much TBH.

sup { vertical-align: top; font-size: 0.6em; }

<img width="857" alt="screen shot 2019-02-04 at 9 10 47 pm" src="https://user-images.githubusercontent.com/11078351/52251231-6207fa80-28c1-11e9-8f3b-dc4b1520dbf4.png">

This is done now. closing. Fixed on #57
