### ISSUE TITLE
New Patches

### ISSUE THREAD

**Issue by Philwave** [surge-synthesizer/surge-synthesizer.github.io#368]
I want to drop Surge patches here... is that possible?
If so, please let me know how. Thanks.

**Comment by Philwave** [comment]
Thanks Andreya

In Surge, in the menu... "Download additional content",
I arrive on this where I see patches to download ... It says in the introduction:
"open an issue in this repository, and we can have your content available on this page."

– this place is directly accessible to the user, so I thought I could put patches there.
– I proposed a pack of 200 patches of 25 MB, 3 days ago, on "Surge content sharing", but it is already invisible.
– I was told to put it on "a site", implying "it's up to you".
– On the Surge site we can read:
"We are looking for people who have content which showcases Surge XT in all of its glory..."
"Let's be kind to each other and treat each other with respect.
It takes all of us working together to make the community great..."

For now I still believe in it a little...

**Comment by Andreya-Autumn** [comment]
Oh right! I had forgotten about that to be honest, sorry! I did see that you posted on DIscord the other day. And for the record, another team member pinned the post so that we can easily find it later. That's easy to miss though, and maybe no one replied directly to your post. Sorry about that! We all have a lot going on sometimes. 

Anyway, usually nowadays when people offer patches it is for inclusion with the 3rd party library which comes with the Surge installer itself. The way that works is a few of us go through the patches and check for some basic compliance (not super strict, things like leveling, naming, not too many or too few, not too similar-sounding etc), after that the patches can be included when we next do a point release of Surge. Next release will be 1.4 sometime this fall most likely. If you want we can do that! Feel free to reply here or on Discord.

Thanks for wanting to contribute and sorry for the unclear communication.

**Comment by Philwave** [comment]
Thanks Andreya, Hi Paul...
Well, let's start again:
I propose a pack of 200 patches, and I wish nothing better
than it to be included in the next version of Surge, if that suits you.
I must say that I would be honored, but it is not up to me to decide.
Of course these patches will have to be listened to and checked by you.
I promise you something very serious that should delight musicians.
- this pack weighs 60 MB, which can be a difficulty to add it to the installer
- the patches use Wavetables of my creation introduced in the installer last year, + new Wavetables + internal oscillators.
- We should also plan to add these new wavetables in the installer:
they reproduce 16 resonance pitches...

That's it for this presentation, and I thank you for allowing me to express myself.
See you soon, Philippe.

**Comment by Andreya-Autumn** [comment]
Any time!

All good if that suits you! You're Phillippe Favre I'm guessing? Adding the new wavetables is certainly no problem. 

You're right that another 60MB (and indeed another 200 patches) is a lot. If it's ok by you, we could select a "best-of" when the time draws near. Or if you'd rather, you can also do that yourself of course! :) 

Thanks again!

**Comment by Philwave** [comment]
Yes I am Philippe Favre.
Yes you could of course select a "best-of"...
But in the future, if Surge came out of confidentiality, wouldn't you have to build a "users" server?

For now, where do I send the pack? Unless you take it here:
https://drive.google.com/drive/folders/1ZPDOOGKhrbegqP-o8-jvvv5VMNf-uKBz?usp=sharing

Concerning the new wavetables, I have to prepare the package. Certainly in a few days...

Thanks

**Comment by Andreya-Autumn** [comment]
I'm not sure what you mean by "confidentiality"? That word usually means "secret", which is not how we work usually?

That link works, I've downloaded the rar. I'll add a note to our release checklist to go through the patches. 

No rush about the wavetables, the release may be another while cause we're mostly busy with other things presently. Tag here or on Discord when ready! :)

**Comment by Philwave** [comment]
Yes... in France, "confidential" also means "very little widespread", "not very visible".
Surge is a machine that is rarely talked about on French sites and it's a shame, even incomprehensible.
I recently posted my opinion at Audiofanzine.com to try to do my bit...

Ok! Thanks again for the pack, enjoy listening, see you soon!
Philippe  - I close that issue

**Comment by Andreya-Autumn** [comment]
Ah ok, I see. Thanks for the support in any case! Take care.
