### ISSUE TITLE
Cannot find the Surge wavetable browser

### ISSUE THREAD

**Issue by PatPast** [surge-synthesizer/surge-synthesizer.github.io#86]
Hello,
it seemed to me that we could open the Surge browser before it's open source ( or before 1.6.0 betas )
I searched on the Surge manual, on the KVR forum for answer and I saw that someone who has bought Surge in the past and has kept this version and he can use the browser as well.
Please update Surge so we can browse the wavetable without changing it one by one with the arrows .
Thanks in advance.

**Comment by baconpaul** [comment]
Hi!

What did the surge wavetable browser do? It's not something which is in the codebase which was open sourced.

Thanks

**Comment by PatPast** [comment]
The Surge wavetable browser was like in this video the 20 first second.  
https://www.youtube.com/watch?v=7mxZOCespLg
Take a look at it and you'll see it's impossible to do this in the actual Surge beta
I hope you see what I mean

**Comment by baconpaul** [comment]
What version are you running? That menu was broken in some ancient first versions but has been working in every version since Dec. In wavetable mode just click on the orange section and the menu appears.

<img width="546" alt="screen shot 2019-03-04 at 6 04 02 pm" src="https://user-images.githubusercontent.com/13387561/53768816-ee4d1380-3ea7-11e9-9ff4-491a4ef5e180.png">

If you aren't running beta 6 please check out https://surge-synthesizer.github.io/ and grab it from there.

**Comment by PatPast** [comment]
Ah! I'm saying things that are false! I can't believe I didn't see this before. In my head, I had to right-click on the orange wavetable title. My bad for me.
Sorry for the inconvenience and thank you for your quick responses to the issues.
